### Authorization API
- request:
    url: ^/api/login$
    method: post
    post: email=hr%40gmail.com&password=123456
  response:
    headers:
      content-type: application/json
    file: api/login/success_hr.json

- request:
    url: ^/api/login$
    method: post
    post: email=email0%40gmail.com&password=Asd123456
  response:
    headers:
      content-type: application/json
    file: api/login/success_user.json

- request:
    url: ^/api/login$
    method: post
    post: email=hr%40gmail.com|email=user0%40gmail.com
  response:
    status: 400
    headers:
      content-type: application/json
    file: api/login/fail_wrong_password.json

- request:
    url: ^/api/login$
    method: post
  response:
    status: 400
    headers:
      content-type: application/json
    file: api/login/fail_not_found.json

### USER API
- request:
    url: ^/api/user$
    method: GET
    headers:
      token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9
  response:
    headers:
      content-type: application/json
    file: api/user/success_get.json

- request:
    url: ^/api/user$
    method: PUT
    headers:
      token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1dWlkIjoiMzU3ODZhNjItNzAwYS00OWRlLTljMzUtZTVkZDk2ZTgzMWU0In0.2u35q2EGYqZMCW7xfnDHb8TMhOy0ricpnGTUDoUVvEc
  response:
    headers:
      content-type: application/json
    file: api/user/success_put.json

- request:
    url: ^/api/user/(35786a62-700a-49de-9c35-e5dd96e831e4|c4397d7c-8f8d-4b61-a760-f05f983b7144|74523e04-debe-47f1-a90a-5fec3f0cc75c|d0e93a07-b99c-4f69-8af9-3cfdba5229ca|30b582c5-11ed-4d4b-96c1-e4edda4f8a0f)$
    method: GET
    headers:
      token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9
  response:
    - headers:
        content-type: application/json
      file: api/user/<% url[1] %>/get.json

- request:
    url: ^/api/user/(35786a62-700a-49de-9c35-e5dd96e831e4|c4397d7c-8f8d-4b61-a760-f05f983b7144|74523e04-debe-47f1-a90a-5fec3f0cc75c|d0e93a07-b99c-4f69-8af9-3cfdba5229ca|30b582c5-11ed-4d4b-96c1-e4edda4f8a0f)$
    method: PATCH
    headers:
      token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1dWlkIjoiMzU3ODZhNjItNzAwYS00OWRlLTljMzUtZTVkZDk2ZTgzMWU0In0.2u35q2EGYqZMCW7xfnDHb8TMhOy0ricpnGTUDoUVvEc
  response:
    - headers:
        content-type: application/json
      file: api/user/<% url[1] %>/patch.json

- request:
    url: ^/api/user/([\da-zA-Z\-]+)$
    method: GET
    headers:
      token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9
  response:
    - headers:
        content-type: application/json
      code: 404
      file: api/user/fail_get_not_found.json

- request:
    url: ^/api/user
  response:
    headers:
      content-type: application/json
    file: api/user/fail_get_unauthorized.json

### Document API
- request:
    url: ^/api/documents$
    method: get
  response:
    latency: 800
    code: 200
    headers:
      content-type: application/json
    file: api/documents/get_document_success.json


- request:
    url: ^/api/documents$
    method: post
  response:
    latency: 800
    code: 201
    headers:
      content-type: application/json
    file: api/documents/post_document_success.json


- request:
    url: ^/api/documents/([0-5])$
    method: delete
  response:
    latency: 800
    headers:
      content-type: application/json
    file: api/documents/<% url[1] %>/delete.json


- request:
    url: ^/api/documents/([0-5])$
    method: patch
  response:
    latency: 800
    headers:
      content-type: application/json
    file: api/documents/<% url[1] %>/patch.json


- request:
    url: ^/api/documents/(.+)$
    method: patch
  response:
    latency: 800
    headers:
      content-type: application/json
    code: 404


- request:
    url: ^/api/documents/(.+)$
    method: delete
  response:
    latency: 800
    headers:
      content-type: application/json
    code: 404


### Salary API
- request:
    url: ^/api/salary$
    method: get
  response:
    headers:
      content-type: application/json
    file: api/salaries/get_salaries_success.json

- request:
    url: ^/api/salary/.$
    method: get
  response:
    headers:
      content-type: application/json
    file: api/salaries/get_user_salary_success.json

- request:
    url: ^/api/salary/.$
    method: put
  response:
    headers:
      content-type: application/json
    file: api/salaries/update_salary_success.json

- request:
    url: ^/api/salary/.$
    method: delete
  response:
    headers:
      content-type: application/json
    file: api/salaries/delete_salary_success.json

- request:
    url: ^/api/salary
    method: post
  response:
    headers:
      content-type: application/json
    file: api/salaries/create_salary_success.json

### ProjectRate API
- request:
    url: ^/api/projectRate
    method: get
  response:
    latency: 800
    code: 200
    headers:
      content-type: application/json
    file: api/projectRate/get_project_rates_success.json

### ProjectWork API
- request:
    url: ^/api/projectWork
    method: get
  response:
    latency: 800
    code: 200
    headers:
      content-type: application/json
    file: api/projectWork/get_project_work_success.json

- request:
    url: ^/api/projectWork
    method: put
  response:
    latency: 800
    code: 200
    headers:
      content-type: application/json
    file: api/projectWork/update_project_work_success.json

### Project API
- request:
    url: ^/api/project
    method: post
    headers:
      token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1dWlkIjoiMzU3ODZhNjItNzAwYS00OWRlLTljMzUtZTVkZDk2ZTgzMWU0In0.2u35q2EGYqZMCW7xfnDHb8TMhOy0ricpnGTUDoUVvEc
  response:
    latency: 800
    code: 200
    headers:
      content-type: application/json
    file: api/project/create_project_success.json

- request:
    url: ^/api/project
    method: get
  response:
    latency: 800
    code: 200
    headers:
      content-type: application/json
      token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1dWlkIjoiMzU3ODZhNjItNzAwYS00OWRlLTljMzUtZTVkZDk2ZTgzMWU0In0.2u35q2EGYqZMCW7xfnDHb8TMhOy0ricpnGTUDoUVvEc
    file: api/project/get_projects_success.json

- request:
    url: ^/api/project
    method: put
  response:
    latency: 800
    code: 200
    headers:
      content-type: application/json
      token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1dWlkIjoiMzU3ODZhNjItNzAwYS00OWRlLTljMzUtZTVkZDk2ZTgzMWU0In0.2u35q2EGYqZMCW7xfnDHb8TMhOy0ricpnGTUDoUVvEc
    file: api/project/update_project_success.json

- request:
    url: ^/api/project
    method: delete
  response:
    latency: 800
    code: 200
    headers:
      content-type: application/json
      token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1dWlkIjoiMzU3ODZhNjItNzAwYS00OWRlLTljMzUtZTVkZDk2ZTgzMWU0In0.2u35q2EGYqZMCW7xfnDHb8TMhOy0ricpnGTUDoUVvEc
    file: api/project/delete_project_success.json
